---

- name: SELinux | RedHat | Install libselinux-python
  yum: name=libselinux-python state=present

- name: SELinux | Set SELinux policy and state
  selinux: policy={{ selinux_policy }} state={{ selinux_state }}
  register: selinux

- block:
  - name: SELinux | Restart machine
    shell: sleep 2 && shutdown -r now "Restarting with SELinux Disabled"
    async: 1
    poll: 0
    ignore_errors: true
  - name: SELinux | Wait for the server to come back
    become: false
    local_action:
      module: wait_for
        host="{{ ansible_host | default(inventory_hostname) }}"
        port="{{ ansible_port | default('22') }}"
        search_regex=".*OpenSSH*"
        delay=10
        timeout=300
    when: selinux.changed and reboot
