---
# Tasks file for RedHat Family
- name: SELinux | Set SELinux policy and state
  selinux: policy={{ selinux_policy }} state={{ selinux_state }}
  register: selinux
- block:
  - name: SELinux | Restart machine
    shell: sleep 2 && shutdown -r now "Restarting with SELinux Disabled"
    async: 1
    poll: 0
    ignore_errors: true
  - name: SELinux | Wait for the server to come back
    local_action: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} search_regex=OpenSSH state=started delay=10 timeout=300
  when: selinux.changed and reboot
